name: clean_architecture_init
description: Flutter Folder Architecture is a thoughtfully designed, pre-built package that simplifies and streamlines your Flutter project setup. It offers a robust and scalable folder structure that follows industry best practices, ensuring your app remains clean, maintainable, and scalable from the very beginning.

version: 1.0.9
repository: https://github.com/hjangir081/flutter_starter.git

environment:
  sdk: '>=3.0.0 <4.0.0'


executables:
  clean_architecture_init: clean_architecture_init


dependencies:
  yaml: ^3.1.3
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  http: ^1.3.0

  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  lints: ^5.0.0
  retrofit_generator: ^9.1.9
  test: ^1.24.0
