name: dotsquares_flutter_starter
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/hjangir081/flutter_starter.git

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
