name: dotsquares_flutter_starter
description: Flutter Folder Architecture is a pre-built, scalable, and organized folder structure package designed to streamline your Flutter project setup. This package provides a well-defined architecture that follows best practices, ensuring clean code separation, maintainability, and scalability for your Flutter applications.
version: 1.0.0
repository: https://github.com/hjangir081/flutter_starter.git

environment:
  sdk: '>=3.0.0 <4.0.0'


executables:
  dotsquares_flutter_starter: "bin/dotsquares_flutter_starter.dart"

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
