name: clean_architecture_init
description: Flutter Folder Architecture is a thoughtfully designed, pre-built package that simplifies and streamlines your Flutter project setup. It offers a robust and scalable folder structure that follows industry best practices, ensuring your app remains clean, maintainable, and scalable from the very beginning.

version: 1.0.8
repository: https://github.com/hjangir081/flutter_starter.git

environment:
  sdk: '>=3.0.0 <4.0.0'


executables:
  dotsquares_flutter_starter: clean_architecture_init


dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
